name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Optional dev requirements for lint/coverage
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run linters (flake8)
        run: |
          if python -c "import pkgutil; exit(0 if pkgutil.find_loader('flake8') else 1)"; then
            echo 'flake8 present, running...'
            flake8 || true
          else
            echo 'flake8 not present, skipping lint step.'
          fi

      - name: Run unit tests with coverage
        run: |
          if python -c "import pkgutil; exit(0 if pkgutil.find_loader('coverage') else 1)"; then
            coverage run -m unittest discover -s tests -v
            coverage xml -i
          else
            python -m unittest discover -s tests -v
          fi
        env:
          FLASK_ENV: test
