name: Build Release Image

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub (skipped)
        run: echo "No registry credentials provided; skipping login"

      - name: Build image
        run: |
          docker build -t ipcm-app:latest .

      - name: Save image artifact
        run: |
          docker save ipcm-app:latest -o ipcm-app-latest.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipcm-app-image
          path: ipcm-app-latest.tar
